FROM openjdk:8-jre-alpine
EXPOSE 8080
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

#crea gruppo app e utente app, poi aggiunge utente al gruppo
RUN addgroup -S app && adduser -S app -G app

#da adesso in poi non eseguire come root ma come user, cosi toglo privilegi non necessari
USER app

ENTRYPOINT ["java", "-jar","/app.jar"]